language: cpp
sudo: required
dist: xenial
cache: bundler

branches:
  only:
    - master
    - travis

matrix:
  include:
  - compiler: clang
    addons:
      apt:
        packages:
        - libopenblas-dev
        - libboost-dev
        - libeigen3-dev
#       - libarmadillo-dev # TODO
  - compiler: gcc
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntu-toolchain-r/test'
        packages:
        - g++-7
        - gfortran-7
        - libopenblas-dev
        - libboost-dev
        - libeigen3-dev
#       - libarmadillo-dev # TODO
    before_install:
      - |
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 \
        --slave /usr/bin/g++ g++ /usr/bin/g++-7                               \
        --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-7

before_script:
  # Stop on first error
  - set -e

  - cd $TRAVIS_BUILD_DIR/..

  # Build and install ARPACK-NG
  - git clone https://github.com/opencollab/arpack-ng.git arpack-ng
  - mkdir arpack-ng.installed
  - pushd arpack-ng
  - |
    cmake .                                                         \
    -DCMAKE_BUILD_TYPE=Release                                      \
    -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/../arpack-ng.installed \
    -DBUILD_SHARED_LIBS=ON
  - make -j3
  - make test
  - make install
  - popd

  # Download and install Blaze
  - git clone https://bitbucket.org/blaze-lib/blaze.git blaze
  - mkdir blaze.installed
  - pushd blaze
  - |
    cmake .                                                         \
    -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/../blaze.installed     \
    -DBLAZE_SHARED_MEMORY_PARALLELIZATION=OFF
  - make install
  - popd

script:
  # Build ezARPACK
  - mkdir ezARPACK.installed
  - mkdir ezARPACK.build && pushd ezARPACK.build
  - |
    cmake ../ezARPACK                                               \
    -DCMAKE_BUILD_TYPE=Release                                      \
    -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/../ezARPACK.installed  \
    -DARPACK_NG_ROOT=$TRAVIS_BUILD_DIR/../arpack-ng.installed       \
    -Dblaze_ROOT=$TRAVIS_BUILD_DIR/../blaze.installed               \
    -DCMAKE_CXX_FLAGS="-Wno-ignored-attributes"
  - make -j3
  - make test
  - make install
  - popd
